import mne
import os
import numpy as np
import matplotlib.pyplot as plt


# --- 1. CONFIGURATION ---
# Change to a motor imagery run
RUN_NUMBER = 'R07'
data_path = f'physionet.org/files/eegmmidb/1.0.0/S001/S001{RUN_NUMBER}.edf' 

LOW_CUTOFF = 0.5   # High-pass filter to remove slow drifts
HIGH_CUTOFF = 40.0 # Low-pass filter to remove muscle artifacts and high-freq noise
NOTCH_FREQ = 60.0  # Notch filter to remove power line noise (use 50.0 for Europe/Asia)
N_CHANNELS_TO_PLOT = 30

# Epoching parameters 
T_START = -1.0  # Start epoch 1.0 seconds before event
T_END = 4.0  # End epoch 4.0 seconds after event
BASELINE = (-1.0, 0.0)  # Baseline correction window
# Relax the rejection criteria for initial testing
REJECT_CRITERIA = dict(eeg=150e-6)  # 150 mv pick to pick

# 2. DATA LOADING & INITIALIZATION 
if os.path.exists(data_path):
    print(f"Loading data from: {data_path}")
    # Read the raw data file, keeping it in memory
    raw = mne.io.read_raw_edf(data_path, preload=True)
    # Apply the standard channel names and montage for EEGBCI data
    mne.datasets.eegbci.standardize(raw) 
    
    # Set the reference to be the average of all channels (common average reference)
    # Using 'average' with proj=True adds the projection but doesn't apply it yet.
    raw.set_eeg_reference('average', projection=True)
else:
    print(f"Error: Data file not found at {data_path}")
    exit()

# 3. PREPROCESSING(Filtering and Visualization)

print("\n--- 3.1: Visualizing RAW Data ---")
# Plot the time series data
raw.plot(scalings='auto', duration=5, n_channels=N_CHANNELS_TO_PLOT, title='Raw EEG Data (Before Filtering)', block=True)

# Compute PSD (Power Spectral Density) using Fourier Transform
# Power Spectral density : measure that describes how the power of a signal
# is distributed over frequency.
# Use a fmax that's half os the sampling rate(Nyquist limit)
psd_raw = raw.compute_psd(fmax=raw.info['sfreq'] / 2)
# Plot the computed PSD
fig_raw = psd_raw.plot()  
# Manually setting the title
fig_raw.suptitle('Power Spectral Density (Before Filtering)', fontsize=16)
plt.show(block=True)

print(f"\n--- 3.2: Applying Bandpass ({LOW_CUTOFF}-{HIGH_CUTOFF}Hz) and Notch ({NOTCH_FREQ}Hz) Filters ---")

# Apply the filters directly to the data 
raw.filter(l_freq=LOW_CUTOFF, h_freq=HIGH_CUTOFF, fir_design='firwin', verbose='WARNING')
raw.notch_filter(freqs=NOTCH_FREQ, fir_design='firwin', verbose='WARNING')

print("\n--- 3.3: Visualizing FILTERED Data ---")
# Plot 5-second segment of the filtered signal
raw.plot(scalings='auto', duration=5, n_channels=N_CHANNELS_TO_PLOT, title='Filtered EEG Data', block=True)
# Compute and PLOT filtered PSD
psd_filtered = raw.compute_psd(fmax=raw.info['sfreq'] / 2)
fig_filtered = psd_filtered.plot(ci=None, show=False)
fig_filtered.suptitle('Power Spectral density (After Filtering)', fontsize=16)
plt.show(block=True)  # This will pause execution until the plot is closed

print("\nPreprocessing (Filtering and Visualization) complete. The 'raw' object is now filtered.")

# --- 4. PARSING & FORMATTING (Epoching) ---

print("\n--- 4.1: Extracting Events and Creating Epochs ---")  # Epoching
# 1. Use events_from_annotations for EEGBCI data
events, event_id_map = mne.events_from_annotations(raw)

print(f"Detected event IDs: {event_id_map}")

print("\n--- 4.1: Extracting the event and creating the epochs ---")
# 2. Select only the task events (T1 and T2) for anlysis.
# This assumes the file contains T1 and T2 (e.g. R03, R07).
EVENT_IDS_TO_KEEP = {}
if 'T1' in event_id_map and 'T2' in event_id_map:
    EVENT_IDS_TO_KEEP = {'T1': event_id_map['T1'], 'T2': event_id_map['T2']}
elif 'T0' in event_id_map:
    EVENT_IDS_TO_KEEP = {'T0': event_id_map['T0']}   # Like R01
else: 
    print("Warning: No recognizable T0, T1 or T2 event found. Check run file.")

# 3. Create fixed-length epochs/trials around the events
# Use the map generated by events_from_annotations.
epochs = mne.Epochs(
    raw, 
    events, 
    # Use event_id_map which containes the 'T0', 'T1', 'T2' IDs.
    event_id=EVENT_IDS_TO_KEEP, 
    tmin=T_START, 
    tmax=T_END, 
    baseline=BASELINE, # Set to None for BCI tasks typically
    # reject=REJECT_CRITERIA,  # Uncomment if wanted artifact rejection
    preload=True   # Load all data segments into memory
)

# 4. Handle Dropped Epochs
print(f"\nSuccessfully created {len(epochs)} epochs.")
if len(epochs) == 0:
    print("Fatal: All epochs are dropped or none were found. Cannot process to feature extraction")
    exit()


# --- 5. PREPARING FOR FEATURE EXTRACTION ---

print("\n--- 5.1: Feature Extraction Example (Power in Frequency Bands) ---")
# Compute the Power Spectral Debsity (PSD) for each epoch using the Epochas object method
spectrum = epochs.compute_psd(method='welch', fmin=0.5, fmax=30., n_fft=128)
psds = spectrum.get_data()
freqs = spectrum.freqs

# Define the standard EEG frequency bands you will extract power from
FREQ_BANDS = {'alpha': [8, 13], 'beta': [13, 30]} # Focusing on alpha/beta for motor imagery

# Initialize a list to hold the features (power in each band for each channel/epoch)
features_list = []

# Loop through the defined bands
for band_name, (fmin, fmax) in FREQ_BANDS.items():
    # Find the frequency indices corresponding to the band
    idx_band = np.logical_and(freqs >= fmin, freqs <= fmax)
    
    # Calculate the average power within that band (for all epochs and all channels)
    mean_power = psds[:, :, idx_band].mean(axis=2) 
    
    # Store this as a feature set
    features_list.append(mean_power)
    
# Combine all features into a single array (Epochs x Features)
X = np.concatenate(features_list, axis=1)

# Get the labels corresponding to the epochs
y = epochs.events[:, -1] # The last column of the events array contains the event ID (1 or 2)

print(f"\n✅ Data fully processed and formatted!")
print(f"Feature Matrix (X) Shape: {X.shape}") # (Number of Epochs, Number of Channels * Number of Bands)
print(f"Label Vector (y) Shape: {y.shape}") # (Number of Epochs,)
print("X and y are ready to be fed into your Machine Learning algorithm.")

